import Link from "next/link";
import {getFoundationMeta,getInstructorMeta,getMeta,getTrackProjectMeta} from "@/lib/course";

export default function Home(){
 const m=getMeta();const f=getFoundationMeta();const i=getInstructorMeta();const projects=getTrackProjectMeta();
 const courseLessons=m.phases.reduce((a,p)=>a+p.lessonCount,0);
 const foundationLessons=f.modules.reduce((a,x)=>a+x.lessonCount,0);
 const guidedLessons=i.tracks.reduce((a,x)=>a+x.lessonCount,0);
 return <main className="shell">
  <section className="hero"><div><div className="eyebrow">Full-Stack Developer 2026</div><h1>Learn the stack by building, breaking, debugging, and shipping a real project.</h1><p>This is a step-by-step full-stack course built around TaskFlow. Lessons start with the simple idea, show a small worked example, tell you what evidence to expect, let you break the behavior safely, and finish with practice you do without copy-paste.</p><div className="actions"><Link className="button" href="/instructor">Start the Guided Course</Link><Link className="button ghost" href="/foundation">I am starting from zero</Link><Link className="button ghost" href="/setup">Set up my machine</Link></div></div><aside className="hero-card"><div className="eyebrow">What you get</div><div className="metrics"><div className="metric"><b>{guidedLessons}</b><span>guided lessons</span></div><div className="metric"><b>{projects.projects.length}</b><span>track projects</span></div><div className="metric"><b>37</b><span>TaskFlow phases</span></div></div><p className="muted">Progress stays in this browser. The documentation site needs no account, database, or backend.</p><div className="actions"><Link className="button ghost" href="/dashboard">Open progress dashboard →</Link></div></aside></section>

  <section className="section"><div className="callout"><b>Not sure where to begin?</b> If HTML, JavaScript, TypeScript, or React still feel new, start in <Link href="/foundation">Foundation</Link>. Otherwise, use the <Link href="/instructor">Guided Course</Link> as the main route and open deep dives or the 37-phase reference curriculum only when you want extra depth.</div></section>

  <section className="section"><div className="eyebrow">Choose your entry point</div><h2>Start where your skills actually are.</h2><div className="grid cards"><Link href="/foundation" className="card big-card"><div className="eyebrow">True beginner</div><h3>Foundation → Frameworks</h3><p className="muted">Learn the web/runtime mental model, HTML/CSS, JavaScript, TypeScript, React, Git, SQL, and API/security fundamentals before relying on frameworks.</p><small>{foundationLessons} foundation lessons</small></Link><Link href="/instructor" className="card big-card"><div className="eyebrow">Main route</div><h3>Guided Course</h3><p className="muted">The detailed code-along path from runtime basics through Next.js, NestJS, PostgreSQL, Prisma, auth, frontend data, testing, Docker, CI/CD, deployment, and enterprise systems.</p><small>{guidedLessons} detailed lessons</small></Link><Link href="/projects" className="card big-card"><div className="eyebrow">Build without the transcript</div><h3>Track Projects</h3><p className="muted">Every major track ends with a project where you collect real evidence and explain the architecture instead of only following steps.</p><small>{projects.projects.length} hands-on projects</small></Link></div></section>

  <section className="section"><div className="eyebrow">How to study</div><h2>Use a simple learning loop.</h2><div className="grid cards"><article className="card"><div className="eyebrow">1 · Understand</div><h3>Say the idea simply.</h3><p className="muted">Before syntax, explain what problem the concept solves and which part of the system owns it.</p></article><article className="card"><div className="eyebrow">2 · Predict + build</div><h3>Make one small change.</h3><p className="muted">Write down what you expect to see, type the example yourself, then run the narrowest useful verification.</p></article><article className="card"><div className="eyebrow">3 · Break + debug</div><h3>Learn from a controlled failure.</h3><p className="muted">Change one assumption, capture the first useful symptom, and fix the earliest boundary where evidence becomes wrong.</p></article><article className="card"><div className="eyebrow">4 · Transfer</div><h3>Close the solution.</h3><p className="muted">Modify the requirement or complete the track project without copying. Reopen only the exact concept you need to review.</p></article></div></section>

  <section className="section"><div className="eyebrow">Reference curriculum</div><h2>Eight volumes, one continuous production-style system</h2><div className="exercise-grid">{m.volumes.map(v=><Link href={`/course/phase-${String(v.phases[0]).padStart(2,"0")}`} className="card" key={v.number}><div className="eyebrow">Volume {String(v.number).padStart(2,"0")}</div><h3>{v.title}</h3><p className="muted">Phases {String(v.phases[0]).padStart(2,"0")}–{String(v.phases.at(-1)).padStart(2,"0")}</p></Link>)}</div><p className="muted">The reference route preserves {courseLessons} lessons/labs from the original 37-phase material. Use it as additional depth, source history, and phase-specific reference.</p></section>

  <section className="section"><div className="two-col"><Link href="/deep-dives" className="card big-card"><div className="eyebrow">When a topic needs slower practice</div><h3>Deep Dives</h3><p className="muted">Extra focused lessons for JavaScript, TypeScript, React, Next.js, NestJS, databases, identity, frontend data, quality engineering, and delivery.</p><small>Predict → run → break → diagnose → transfer</small></Link><Link href="/milestones" className="card big-card"><div className="eyebrow">Larger closed-reference work</div><h3>Mastery Milestones</h3><p className="muted">Combine several tracks and prove you can build, verify, debug, and explain a bigger slice independently.</p><small>Static TaskFlow → Enterprise capstone</small></Link></div></section>

  <section className="section"><div className="pedagogy-banner"><div><div className="eyebrow">The standard</div><h2>Reading is useful. Reproducing the skill is the goal.</h2></div><p>By the end of a topic, you should know why it exists, where it belongs, how to prove it works, what a realistic failure looks like, and how to adapt it when the requirement changes.</p></div></section>
  <section className="section"><div className="callout"><b>Technology contract.</b> {m.courseLocks.join(" · ")}. The course keeps these versions stable so you can focus on concepts. Upgrade deliberately only after reading migration notes and rerunning checkpoints.</div></section>
 </main>
}
