import Link from "next/link";
import {CodeBlock} from "@/components/code-block";
const steps=[
 {t:"1. Understand what you are installing",p:"You need an editor, shell, Git, a Node version line, Corepack/pnpm, browser DevTools, and later external services such as PostgreSQL/Supabase and Docker. Treat each as a separate executable/service you can verify.",code:"Get-Location\n$PSVersionTable.PSVersion"},
 {t:"2. Install Git and verify command resolution",p:"Use a normal user-level installation where appropriate. Open a fresh PowerShell after installation and prove which executable is being resolved before assuming setup succeeded.",code:"Get-Command git\ngit --version\ngit config --global user.name\ngit config --global user.email"},
 {t:"3. Install VS Code and learn the terminal boundary",p:"VS Code is an editor, not the runtime. Its integrated terminal inherits environment variables from the editor process, so restart the editor when PATH changes are not visible.",code:"code --version"},
 {t:"4. Install the course Node line through a version manager",p:"A version manager makes project runtimes reproducible. The repository/course may lock a specific Node line; use that lock instead of whatever global installer happens to be newest.",code:"Get-Command node\nnode --version\nnpm --version"},
 {t:"5. Enable Corepack and activate pnpm",p:"Corepack lets the repository declare the package-manager version. Do not maintain unrelated global pnpm installations if they cause command-resolution confusion.",code:"corepack --version\ncorepack enable\npnpm --version"},
 {t:"6. Clone or extract the repository into a normal user-owned folder",p:"Avoid protected system folders. Keep project paths simple enough that scripts/tools do not inherit permission problems from Program Files or system directories.",code:"git status\nGet-Location"},
 {t:"7. Install dependencies reproducibly",p:"The lockfile is part of the project contract. On the first install, pnpm creates pnpm-lock.yaml. Commit it. After that, use --frozen-lockfile in CI/verification so dependency resolution cannot drift silently.",code:"pnpm install"},
 {t:"8. Run the documentation site",p:"Start the dev server, read the exact listening address, and verify the browser request. If the port is occupied, find the owning process rather than killing random Node processes.",code:"pnpm dev\nGet-NetTCPConnection -State Listen | Sort-Object LocalPort"},
 {t:"9. Run production verification before Vercel",p:"Development mode is not proof that the project builds. Run type checking and the production build from a clean state before pushing.",code:"pnpm lint\npnpm build"},
 {t:"10. Keep secrets and environment-specific values out of Git",p:"The documentation site itself needs no database secrets. When you build TaskFlow, use .env files excluded from Git and commit only safe examples documenting required variable names.",code:"git status\ngit diff -- .gitignore"},
];
const trouble=[
 ["pnpm is not recognized","Run Get-Command pnpm, check Corepack, open a fresh terminal, and identify whether another pnpm executable shadows the intended one."],
 ["EPERM / access denied","Check whether the project/tool is writing under a protected directory or another process is holding the file. Do not default to Administrator mode as the permanent fix."],
 ["Port 3000/4000 already in use","Find the PID owning the listening port, identify the process, then stop only the service you actually mean to stop."],
 ["Node version is wrong","Use Get-Command node and your version manager's current selection. PATH order can point to an older standalone installation."],
 ["Build differs from dev","Read the production build error first. Server/client boundaries, type errors, static generation, and environment values often surface only during build."],
];
export default function Setup(){return <main className="shell narrow-shell"><section className="phase-head"><div className="eyebrow">Zero-to-ready · Windows-focused setup</div><h1>Set up the environment and learn how to prove it works.</h1><p>This is intentionally more than an installer checklist. The goal is that you can diagnose PATH, permissions, processes, ports, runtime versions, and package-manager failures before framework code enters the picture.</p></section><section className="section"><div className="setup-long">{steps.map((s,i)=><article className="setup-block" key={i}><div><div className="eyebrow">Environment step</div><h2>{s.t}</h2><p>{s.p}</p></div><CodeBlock code={s.code} label="PowerShell" caption="Verification"/></article>)}</div></section><section className="section"><div className="eyebrow">Troubleshooting</div><h2>Do not solve setup failures by randomly reinstalling everything.</h2><div className="error-playbook">{trouble.map(([t,p])=><article className="error-card" key={t}><h3>{t}</h3><p>{p}</p></article>)}</div></section><section className="section"><div className="callout"><b>Ready means verified:</b> a fresh ordinary PowerShell can resolve the intended Git/Node/Corepack/pnpm executables, the repository installs from its lockfile, dev starts, and production build/type checks pass.</div></section><div className="actions"><Link className="button" href="/foundation/f08">Learn terminal/tooling deeply</Link><Link className="button ghost" href="/course/phase-01">Phase 01 professional tooling →</Link></div></main>}
