import {notFound} from "next/navigation";
import Link from "next/link";
import {getFoundationLesson,getFoundationMeta,getFoundationModule} from "@/lib/course";
import {LessonBody} from "@/components/lesson-body";
import {CompleteButton} from "@/components/progress";
import {FoundationPractice} from "@/components/foundation-practice";
import {LessonVisit} from "@/components/lesson-visit";
export function generateStaticParams(){return getFoundationMeta().modules.flatMap(m=>{const x=getFoundationModule(m.slug)!;return x.lessons.map(l=>({module:m.slug,lesson:l.slug}))})}
export default async function FoundationLessonPage({params}:{params:Promise<{module:string;lesson:string}>}){const a=await params;const x=getFoundationLesson(a.module,a.lesson);if(!x)notFound();const {module,lesson}=x;const idx=module.lessons.findIndex(l=>l.slug===lesson.slug);const prev=module.lessons[idx-1],next=module.lessons[idx+1];return <main className="lesson"><LessonVisit href={`/foundation/${module.slug}/${lesson.slug}`} title={lesson.title} kind={`Foundation · ${module.title}`}/><div className="eyebrow"><Link href={`/foundation/${module.slug}`}>Foundation F{String(module.number).padStart(2,'0')}</Link> · Lesson {String(lesson.number).padStart(2,'0')}</div><h1>{lesson.title}</h1><div className="lesson-meta">≈ {Math.max(3,Math.round(lesson.wordCount/210))} min · beginner prerequisite</div><section className="section"><div className="lesson-contract"><div><div className="eyebrow">Objectives</div><h2>By the end</h2><ul>{lesson.objectives.map((o,i)=><li key={i}>{o}</li>)}</ul></div><aside><div className="eyebrow">Foundation rule</div><p>Predict what the computer will do before running the example. The prediction is what turns output into evidence.</p></aside></div></section><LessonBody text={lesson.body}/>{lesson.practice&&<FoundationPractice practice={lesson.practice}/>}<section className="section"><div className="practice-box"><div className="eyebrow">Practice before completion</div><h2>Small experiment, intentional failure, explain-back</h2><p>Build the smallest example that demonstrates this lesson. Then break one relevant assumption and diagnose it using terminal/DevTools evidence. Finally explain the concept without using a framework name.</p></div><CompleteButton id={`foundation:${module.slug}:${lesson.slug}`}/></section><div className="actions lesson-actions">{prev&&<Link className="button ghost" href={`/foundation/${module.slug}/${prev.slug}`}>← {prev.title}</Link>}{next?<Link className="button" href={`/foundation/${module.slug}/${next.slug}`}>{next.title} →</Link>:<Link className="button" href={`/foundation/${module.slug}`}>Module review →</Link>}</div></main>}
